version: '3'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zulf
      MONGO_INITDB_ROOT_PASSWORD: pekmafn

  rospis:
    image: zulf4/rospis-kgeu
    restart: always
    env_file:
      - .dev.env
    ports:
      - 80:80
